apiVersion: v1
kind: Pod
metadata:
  name: test-pod-hostpath
  labels:
    name: test-pod-hostpath
spec:
  containers:
  - name: test-pod-hostpath
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: test-hostpath
        mountPath: /test-hostpath
      - name: test-emptydir
        mountPath: /test-emptydir
    command: ['sh', '-c', 'while true;do sleep 3600; done']
  volumes:
    - name: test-hostpath
      hostPath:
        path: /tmp/sample
        type: DirectoryOrCreate
        # 無ければつくってよい
    - name: test-emptydir
      emptyDir: {}


