apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: test-volume
        mountPath: /test-volume
    command: ['sh', '-c', 'while true;do sleep 3600; done']
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
