### yourname/hostbot:v1 というイメージを使ったPodを作成するデプロイメント
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostbot
  labels:
    name: hostbot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hostbot
  template:
    metadata:
      labels:
        name: hostbot
    spec:
      containers:
      - name: hostbot
        # イメージ名は各自のDockerHubアカウントにあわせて調整すること!
        image: yourname/hostbot:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
