apiVersion: apps/v1
kind: Deployment
metadata:
  name: failweb
spec:
  selector:
    matchLabels:
      app: failweb
  template:
    metadata:
      labels:
        app: failweb
    spec:
      containers:
      - name: failweb
        image: densukest/failweb:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 3 # 3回失敗したらコンテナ再起動
        ports:
        - containerPort: 80
