# Ubuntu 24.04を単純に起動しておく設定
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        # sleepコマンドで無限に寝ていてもらう
        command: ["sleep", "infinity"]

