# サイドカーパターンを利用して、Webサービスとログ収集サービスを連携する
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-logger
  template:
    metadata:
      labels:
        app: web-logger
    spec:
      containers:
      - name: web
        image: nginx:1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        volumeMounts:
        - name: log
          mountPath: /var/log/nginx
      - name: logger
        image: busybox
        args: [/bin/sh, -c, 'while true; do echo $(date) - Hello, Kubernetes! >> /var/log/app.log; sleep 5; done']
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: log
          mountPath: /var/log
      volumes:
      - name: log
        emptyDir: {}
